import type {Draft} from './drafts.js';
import {designedDocument,designs,escape,type DesignId} from './design.js';
import {sceneSvg,slideScenes} from './slide-design.js';
export function designPreview(d:Draft,t:string,id:DesignId='navy'){
 if(t==='lesson-package')return designedDocument(d,'lesson-plan',id);
 if(t==='slides')return `<!doctype html><html lang="ko"><meta charset="utf-8"><style>body{margin:0;background:#e9edf2;padding:20px;font-family:sans-serif}article{max-width:1000px;margin:0 auto 22px;box-shadow:0 6px 25px #18324f18}svg{display:block;width:100%;height:auto}</style><body>${slideScenes(d,id).map(scene=>`<article>${sceneSvg(scene)}</article>`).join('')}</body></html>`;
 if(t==='tracker'){
 const p=designs[id],status=d.columns.findIndex(c=>/상태|진행/.test(c)),done=d.rows.filter(r=>r[status]==='완료').length,active=d.rows.filter(r=>r[status]==='진행 중').length;
 return `<!doctype html><html lang="ko"><meta charset="utf-8"><style>body{margin:0;padding:26px;font-family:'Apple SD Gothic Neo',Arial,sans-serif;color:${p.ink};background:#F1F4F7}header{background:${p.ink};color:white;padding:25px 30px;border-radius:8px}header small{letter-spacing:3px}h1{font-size:27px;margin:14px 0}p{font-size:12px;line-height:1.6}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metric{background:white;border-top:3px solid ${p.accent};padding:18px}.metric strong{font-size:34px;display:block;margin:14px 0}.metric span{font-size:11px}.chart{display:flex;align-items:center;gap:24px;background:white;padding:20px;margin:18px 0}.ring{width:90px;height:90px;border-radius:50%;background:conic-gradient(${p.accent} ${done/Math.max(1,d.rows.length)*360}deg,${p.pale} 0);display:grid;place-items:center}.ring i{width:63px;height:63px;background:white;border-radius:50%;display:grid;place-items:center;font-style:normal;font-weight:bold}table{border-collapse:collapse;width:100%;background:white;font-size:12px}th{text-align:left;background:${p.ink};color:white;padding:14px}td{padding:13px;border-bottom:1px solid #DFE6EE}tr:nth-child(odd){background:${p.pale}}td span{padding:5px 10px;background:#E1EFE5;border-radius:16px;white-space:nowrap}.tabs{margin-top:14px;padding:12px;background:white;font-size:12px}.tabs b{color:${p.accent};padding:12px;border-bottom:3px solid ${p.accent}}@media(max-width:550px){body{padding:12px}.metrics{gap:6px}.metric{padding:10px}.metric strong{font-size:23px}table{font-size:10px}td,th{padding:8px}header{padding:18px}}</style><body><header><small>PROJECT OVERVIEW</small><h1>${escape(d.title)}</h1><p>${escape(d.summary)}</p></header><section class="metrics">${[['전체 업무',d.rows.length],['완료',status<0?'—':done],['진행 중',status<0?'—':active],['예정 / 기타',status<0?'—':d.rows.length-done-active]].map(([label,num])=>`<div class="metric"><span>${label}</span><strong>${num}</strong></div>`).join('')}</section>${status>=0?`<div class="chart"><div class="ring"><i>${Math.round(done/Math.max(1,d.rows.length)*100)}%</i></div><div><b>함께 만드는 진행 상황</b><p>Google Sheets에서 상태를 변경하면<br>요약 수식과 차트가 자동으로 바뀝니다.</p></div></div>`:''}<h2>실행 보드</h2><table><thead><tr>${d.columns.map(c=>`<th>${escape(c)}</th>`).join('')}</tr></thead><tbody>${d.rows.map(r=>`<tr>${r.map((c,i)=>`<td>${i===status?'<span>':''}${escape(c)}${i===status?'</span>':''}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="tabs"><b>대시보드</b>　실행 보드</div></body></html>`;
 }
 if(t==='quiz')return `<!doctype html><html lang="ko"><meta charset="utf-8"><style>body{font-family:'Apple SD Gothic Neo',Arial,sans-serif;background:#F0EBF8;color:#292431;max-width:690px;margin:auto;padding:24px}header,article{background:white;border:1px solid #DADCE0;border-radius:10px;padding:24px;margin-bottom:16px}header{border-top:10px solid #673AB7}h1{font-size:27px;margin:8px 0}h2{font-size:17px;line-height:1.5}p{font-size:13px;line-height:1.7}small{color:#6C617B}.option{border:1px solid #E4DFEB;border-radius:7px;padding:12px;margin:8px 0;font-size:13px}.feedback{background:#EDF7EF;color:#245B35;padding:12px;border-radius:6px;font-size:12px;line-height:1.7}.label{font-size:11px;letter-spacing:2px;color:#673AB7}.note{color:#665A78;font-size:12px}</style><body><header><span class="label">LEARNING CHECK</span><h1>${escape(d.title)}</h1><p>${escape(d.summary)}</p><small>${d.questions.length}문항 · ${d.questions.reduce((n,q)=>n+q.points,0)}점</small></header>${d.questions.map((q,i)=>`<article><span class="label">QUESTION ${String(i+1).padStart(2,'0')}</span><h2>${escape(q.title)}</h2>${q.choices.map(c=>`<div class="option">○　${escape(c)}</div>`).join('')}<div class="feedback"><b>정답·해설 검토</b><br>${escape(q.correctAnswer)}${q.explanation?'<br>'+escape(q.explanation):''}</div></article>`).join('')}<p class="note">문항 구성 미리보기입니다. 실제 Forms의 색상·글꼴은 연결된 원본 테마 또는 Forms 기본 테마를 사용합니다. 정답·해설은 검토용이며 응답 화면에 질문과 함께 노출되지 않습니다.</p></body></html>`;
 return designedDocument(d,t,id);
}
