import MarkdownIt from 'markdown-it';
import {designSchema,type DesignId} from './design-schema.js';
export {designSchema,type DesignId} from './design-schema.js';
import type { Draft } from './drafts.js';
import { draftMarkdown } from './drafts.js';
import type { MarkdownToHwpxOptions, FormatProfile } from 'kordoc';
import {tableWeights} from '../google/table-layout.js';
export const designs={
 navy:{name:'클래식 리포트',description:'정돈된 보고서 · 수업안',ink:'#18324F',accent:'#157C80',pale:'#EAF2F5',paper:'#FFFFFF',muted:'#607388'},
 blue:{name:'모던 워크스페이스',description:'팀 협업 · 발표 · 프로젝트',ink:'#174EA6',accent:'#1967D2',pale:'#E8F0FE',paper:'#FFFFFF',muted:'#5F6B7A'},
 warm:{name:'웜 에디토리얼',description:'독서 · 모임 · 생활 기록',ink:'#633D2A',accent:'#A35423',pale:'#F8EEDF',paper:'#FFFCF7',muted:'#786B61'}
};
export const escape=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function rgb(hex:string){return {red:parseInt(hex.slice(1,3),16)/255,green:parseInt(hex.slice(3,5),16)/255,blue:parseInt(hex.slice(5,7),16)/255};}
const labels:Record<string,string>={'lesson-plan':'교수·학습 과정안','lesson-package':'수업 디자인','worksheet':'탐구 활동지','quiz':'형성평가','slides':'발표 자료','tracker':'프로젝트 관리','report':'기획 제안서','notice':'안내문','minutes':'회의 기록','event-plan':'운영 계획','study-notes':'리딩 저널','travel-plan':'여행 플래너'};
const cell=(s:string)=>s.replace(/\|/g,'／').replace(/\n/g,' · ');
export function designedMarkdown(d:Draft,t:string):string{
 if(t==='lesson-package')return ['lesson-plan','worksheet','slides','quiz'].map(kind=>designedMarkdown(d,kind)).join('\n\n---\n\n');
 if(t==='lesson-plan')return `# ${d.title}\n\n> ${d.summary}\n\n| 학습 목표 | 수업 시간 |\n| --- | --- |\n| ${cell(d.objective)} | ${d.steps.reduce((n,s)=>n+s.minutes,0)}분 |\n\n## 수업 흐름 한눈에\n| 단계 | 활동 | 시간 |\n| --- | --- | --- |\n${d.steps.map(s=>`| ${cell(s.stage)} | ${cell(s.process)} | ${s.minutes}분 |`).join('\n')}\n\n## 교수·학습 과정\n| 단계 · 시간 | 학습 과정 | 교수·학습 활동 |\n| --- | --- | --- |\n${d.steps.map(s=>`| ${cell(s.stage)} · ${s.minutes}분 | ${cell(s.process)} | ${s.activities.map(cell).join('<br>')} |`).join('\n')}\n\n${d.markdown}`;
 if(t==='worksheet')return `# ${d.title}\n\n> ${d.objective}\n\n| 학년 · 반 | 이름 | 날짜 |\n| --- | --- | --- |\n| __________ | __________ | __________ |\n\n`+d.activities.map((a,i)=>`## ${String(i+1).padStart(2,'0')}  ${a.title}\n${a.prompt}\n\n| 나의 생각과 근거 |\n| --- |\n${Array(Math.max(2,a.lines)).fill('| 　　　　　　　　　　　　　　　　　　　　　　　　 |').join('\n')}`).join('\n\n');
 if(t==='quiz')return `# ${d.title}\n\n> ${d.summary}\n\n${d.questions.length}문항 · 총 ${d.questions.reduce((s,q)=>s+q.points,0)}점\n\n`+d.questions.map((q,i)=>`## ${String(i+1).padStart(2,'0')}  ${q.title}\n${q.choices.map((c,j)=>`${'①②③④⑤⑥'[j]} ${c}`).join('\n\n')}\n\n**정답** ${q.correctAnswer} · ${q.points}점${q.explanation?'\n\n**해설** '+q.explanation:''}`).join('\n\n');
 return draftMarkdown(d,t);
}
function styledMarkdown(markdown:string,id:DesignId){
 const p=designs[id],md=new MarkdownIt({html:false,breaks:true});let row=0,col=0,weights:number[]=[];
 md.renderer.rules.table_open=(tokens,index)=>{const headers:string[]=[];for(let i=index+1;i<tokens.length&&tokens[i].type!=='thead_close';i++)if(tokens[i].type==='inline')headers.push(tokens[i].content);weights=tableWeights(headers);row=0;return '<table style="width:100%;border-collapse:collapse;margin:10pt 0 15pt;table-layout:fixed">';};
 md.renderer.rules.tr_open=()=>{row++;col=0;return '<tr>';};
 md.renderer.rules.th_open=()=>`<th style="width:${(weights[col++]??1)*100}%;padding:8pt 9pt;background:${p.ink};color:#FFFFFF;border:0.6pt solid ${p.ink};font-size:9.5pt;text-align:left;vertical-align:middle">`;
 md.renderer.rules.td_open=()=>`<td style="padding:8pt 9pt;background:${row%2?'#F5F7FA':'#FFFFFF'};border:0.6pt solid #CCD5DF;font-size:9.5pt;vertical-align:top;overflow-wrap:anywhere">`;
 let n=0;md.renderer.rules.heading_open=(tokens,index)=>{const tag=tokens[index].tag;if(tag==='h1')return `<h1 style="font-size:24pt;line-height:1.3;color:${p.ink};margin:0 0 10pt">`;if(tag==='h2'){n++;return `<h2 style="font-size:13pt;color:${p.ink};margin:22pt 0 9pt;page-break-after:avoid"><span style="color:${p.accent}">${String(n).padStart(2,'0')}　</span>`;}return `<${tag} style="font-size:11pt;color:${p.ink};margin:14pt 0 6pt">`;};
 md.renderer.rules.blockquote_open=()=>`<table style="width:100%;border-collapse:collapse;margin:10pt 0 16pt"><tr><td style="border-left:3pt solid ${p.accent};background:${p.pale};padding:11pt 14pt;color:${p.ink};font-size:10pt">`;
 md.renderer.rules.blockquote_close=()=>'</td></tr></table>';
 md.renderer.rules.paragraph_open=()=>'<p style="margin:4pt 0 8pt;line-height:1.65">';
 // Break markers generated by our structured tables are safe; raw user HTML stays escaped.
 return md.render(markdown).replace(/&lt;br&gt;/g,'<br>');
}
export function designedDocument(d:Draft,t:string,id:DesignId='navy',source=''){
 const p=designs[id],kind=labels[t]??'문서';
 let markdown=designedMarkdown(d,t).replace(/^# [^\n]*\n/,'');
 if(markdown.trimStart().startsWith('> '+d.summary+'\n'))markdown=markdown.trimStart().slice(d.summary.length+3);
 const header=`<table style="width:100%;border-collapse:collapse;margin-bottom:22pt"><tr><td style="color:${p.accent};font-size:9pt;font-weight:bold;padding:0 0 9pt;border-top:none;border-left:none;border-right:none;border-bottom:2.5pt solid ${p.ink}">WORKSPACE LAB　 /　 ${escape(kind)}</td><td style="text-align:right;font-size:8pt;color:${p.muted};padding:0 0 9pt;border-top:none;border-left:none;border-right:none;border-bottom:2.5pt solid ${p.ink}">${escape(designs[id].name)}</td></tr></table><h1 style="font-size:25pt;line-height:1.3;font-weight:bold;color:${p.ink};margin:0 0 10pt">${escape(d.title)}</h1><p style="font-size:10.5pt;line-height:1.6;color:${p.muted};margin:0 0 20pt">${escape(d.summary)}</p>`;
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><style>@page{size:A4;margin:18mm 18mm 17mm}*{box-sizing:border-box}body{font-family:'Noto Sans KR','Apple SD Gothic Neo',sans-serif;font-size:10pt;line-height:1.6;color:#263645;margin:0;background:${p.paper}}h1,h2,h3{break-after:avoid}tr{break-inside:avoid}td p,th p{margin:0}thead{display:table-header-group}ul,ol{padding-left:18pt}li{margin:5pt 0}img{max-width:100%}.doc-page{max-width:680px;margin:auto;padding:32px 26px}@media print{.doc-page{max-width:none;padding:0;margin:0}}</style></head><body><article class="doc-page">${header}${styledMarkdown(markdown,id)}${source?`<h2>참고 성취기준</h2><p>${escape(source)}</p>`:''}<p style="margin-top:22pt;padding-top:8pt;border-top:0.6pt solid #D6DDE6;font-size:8pt;color:${p.muted}">${escape(kind)}　•　Workspace Lab</p></article></body></html>`.replace(/>\s+</g,'><');
}
export function hwpxOptions(markdown:string,id:DesignId='navy'):MarkdownToHwpxOptions{
 const p=designs[id],tokens=new MarkdownIt({html:false}).parse(markdown,{}),profile:FormatProfile={schema_version:'0.3.0',tables:[]};
 for(let i=0;i<tokens.length;i++)if(tokens[i].type==='table_open'){
  const rows:string[][]=[];let cells:string[]=[];
  for(i++;i<tokens.length&&tokens[i].type!=='table_close';i++){if(tokens[i].type==='tr_open')cells=[];if(tokens[i].type==='inline')cells.push(tokens[i].content);if(tokens[i].type==='tr_close')rows.push(cells);}
  const cols=rows[0]?.length??0;if(!cols)continue;
  const width=48188;const weights=tableWeights(rows[0]);
  const border={type:'SOLID',width:'0.12 mm',color:'#C8D2DD'};
  profile.tables.push({table_index:profile.tables.length,rows:rows.length,cols,anchor_text:rows[0][0],width_hwpunit:String(width),col_widths_hwpunit:weights.map(n=>String(Math.round(width*n))),cells:rows.flatMap((r,ri)=>r.map((_,ci)=>({row:ri,col:ci,borderFillIDRef:ri===0?'head':ri%2?'white':'pale',charPrIDRef:ri===0?'head':'body'}))),used_border_fills:{head:{fill:{faceColor:p.ink},leftBorder:border,rightBorder:border,topBorder:border,bottomBorder:border},white:{fill:{faceColor:'#FFFFFF'},leftBorder:border,rightBorder:border,topBorder:border,bottomBorder:border},pale:{fill:{faceColor:p.pale},leftBorder:border,rightBorder:border,topBorder:border,bottomBorder:border}},used_char_prs:{head:{height_hwpunit:'950',textColor:'#FFFFFF',bold:true,fontName_hangul:'맑은 고딕'},body:{height_hwpunit:'950',textColor:'#263645',fontName_hangul:'맑은 고딕'}}});
 }
 return {theme:{headingColors:{1:p.ink,2:p.ink,3:p.accent},bodyColor:'#263645',tableHeaderColor:'#FFFFFF',tableHeaderBold:true},profile,page:{size:'A4',header:'WORKSPACE LAB  /  '+p.name,footer:'Workspace Lab'},gongmun:{preset:'report',bodyFont:'gothic',bodyPt:10.5,lineSpacing:155,centerTitle:false,cover:false,toc:false,endMark:false,pageNumbers:true,h2Marker:'band',bandColor:p.ink,bandTextColor:'#FFFFFF',margins:{top:18,bottom:17,left:18,right:18},fonts:{body:'맑은 고딕',heading:'맑은 고딕',table:'맑은 고딕'},sizes:{table:9.5},autoFit:false}};
}
