CREATE TABLE IF NOT EXISTS state(key TEXT PRIMARY KEY,payload TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS state_expiry ON state(expires);
CREATE TABLE IF NOT EXISTS quota(key TEXT NOT NULL,day TEXT NOT NULL,used INTEGER NOT NULL,PRIMARY KEY(key,day));
